start-instance:
    docker compose up --detach --renew-anon-volumes --force-recreate --wait

stop-instance:
    docker compose down

get-console:
    psql --dbname "$CONNECTION_STRING"

restart-instance:
    docker compose restart

create-dataset:
    time psql --dbname "$CONNECTION_STRING" --file create-dataset.sql

export-table:
    time psql --dbname "$CONNECTION_STRING" --file="export-table.sql"

import-table:
    time psql --dbname "$CONNECTION_STRING" --file="import-table.sql"

import-table-unlogged:
    time psql --dbname "$CONNECTION_STRING" --file="import-table-unlogged.sql"

get-database-size:
    psql --dbname "$CONNECTION_STRING" --command="SELECT pg_size_pretty(pg_database_size('$POSTGRESQL_DATABASE_NAME'));"