# Source:
# - documentation: https://hub.docker.com/_/postgres

services:

  postgresql:
    container_name: postgresql
    image: ${POSTGRESQL_IMAGE_NAME}:${POSTGRESQL_IMAGE_VERSION}
    ports:
      - "${POSTGRESQL_EXPOSED_PORT}:${POSTGRESQL_INTERNAL_PORT}"
    # https://www.postgresql.org/docs/current/app-postgres.html
    command: docker-entrypoint.sh -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_USER_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE_NAME}
    healthcheck:
      test: "psql --dbname \"host=localhost port=${POSTGRESQL_INTERNAL_PORT} dbname=${POSTGRESQL_DATABASE_NAME} user=${POSTGRESQL_USER_NAME} password=${POSTGRESQL_USER_PASSWORD}\""
      interval: 1s
      timeout: 10s
      retries: 20
    volumes:
      - ./configuration/postgresql.${PG_MODE}.conf:/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '${POSTGRESQL_CPU_COUNT}'
          memory: ${POSTGRESQL_TOTAL_MEMORY_SIZE}