#set dotenv-filename := env.just
set shell := ["powershell.exe", "-c"]

start-instance:
    docker compose up --detach --renew-anon-volumes --force-recreate --wait
    psql --dbname "$CONNECTION_STRING_ADMIN" --file configure-instance.sql

stop-instance:
    docker compose down

restart-instance:
    docker compose restart

console:
   PSQLRC=".psqlrc.readonly" psql --dbname "$CONNECTION_STRING"

create-medium-dataset:
    psql --dbname "$CONNECTION_STRING" --file create-medium-dataset.sql

create-big-dataset:
    psql --dbname "$CONNECTION_STRING" --file create-big-dataset.sql

create-huge-dataset:
    psql --dbname "$CONNECTION_STRING" --file create-huge-dataset.sql